"""collection images

Revision ID: 4adc397b6e2e
Revises: 68f505b30806
Create Date: 2025-01-14 22:18:23.472763

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '4adc397b6e2e'
down_revision = '68f505b30806'
branch_labels = None
depends_on = None


def upgrade():
    schema = os.environ.get("SCHEMA") if environment == 'production' else None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_images')
    # ### end Alembic commands ###
