"""alter users table

Revision ID: ac0b2f86c223
Revises: ffdc0a98111c
Create Date: 2025-01-09 17:50:39.512260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0b2f86c223'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add the first_name column as nullable initially
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # Populate existing rows with a default value for first_name
    op.execute("UPDATE users SET first_name = 'Default Name' WHERE first_name IS NULL")

    # Alter the first_name column to be NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name', nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('bio')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
