"""remove visibility fields

Revision ID: 525bd23f6a0b
Revises: 33fff09bf61d
Create Date: 2025-01-16 22:29:18.990568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525bd23f6a0b'
down_revision = '33fff09bf61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_recipes', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'Public'"), nullable=False))

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('collection_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'Everyone'"), nullable=False))

    # ### end Alembic commands ###
